# Travis-CI for libnss-rightlink
language: c

# sudo=false makes the build run using a container
sudo: false

script:
  - ./bootstrap
  - ./configure
  - make
  - gcc -g test.c -o run_tests shadow.o utils.o passwd.o group.o
  - ./run_tests

